### ISSUE TITLE
Error while provisioning

### ISSUE THREAD

**Issue by dimitrismistriotis** [shishir/single-node-hadoop#1]
I am receiving the following error:

```
[2014-01-28T12:30:17+00:00] ERROR: Running exception handlers
[2014-01-28T12:30:17+00:00] ERROR: Exception handlers complete
[2014-01-28T12:30:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-01-28T12:30:17+00:00] FATAL: Net::HTTPServerException: remote_file[/tmp/hadoop-1.2.0.tar.gz] (hadoop::install line 1) had an error: Net::HTTPServerException: 404 "Not Found"
```

Any ideas on what I am doing wrong?

**Comment by shishir** [comment]
hadoop 1.2.0 is no longer available i guess. I have upgraded it to 1.2.1.

Give it a try and let me know if that doesn't work

On Tue, Jan 28, 2014 at 6:02 PM, Dimitrios Mistriotis <
notifications@github.com> wrote:

> I am receiving the following error:
> 
> [2014-01-28T12:30:17+00:00] ERROR: Running exception handlers
> [2014-01-28T12:30:17+00:00] ERROR: Exception handlers complete
> [2014-01-28T12:30:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
> [2014-01-28T12:30:17+00:00] FATAL: Net::HTTPServerException: remote_file[/tmp/hadoop-1.2.0.tar.gz](hadoop::install line 1) had an error: Net::HTTPServerException: 404 "Not Found"
> 
> Any ideas on what I am doing wrong?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/shishir/single-node-hadoop/issues/1
> .

## 

Regards,
Shishir Das
m: +91.9923700610 | g-talk: shishir.das@gmail.com | skype: shishir_n_das

**Comment by dimitrismistriotis** [comment]
Closing issue, do not even know if it is still relevant.
